title: Efrat Levitan
description: >
  Efrat Levitan's Blog site 
baseurl: "/blog"
url: "http://efrat19.github.io"

author:
  name: Efrat Levitan
  email: efrat890089gmail.com
  github: Efrat19
  twitter: EfratLevitan
  linkedin: efrat-levitan-773402177
  disqus_shortname: https-efrat19-github-io

paginate: 3
paginate_path: page:num

sass:
  style: expanded

plugins:
  - jekyll-paginate
  - jekyll-feed
